import os

BUCKET_NAME = os.environ["YTDL_BUCKET_NAME"]
JWT_NO_HIMITSU = os.environ["JWT_NO_HIMITSU"]
KAKUSU_HIMITSU = os.environ["KAKUSU_HIMITSU"]
DOMAIN = os.environ["DOMAIN"]
MAX_USER_TASK = int(os.environ["MAX_USER_TASK"])
MASTER_SIGNUP_CODE = os.environ["MASTER_SIGNUP_CODE"]
MASTER_TOKEN = os.environ["MASTER_TOKEN"]
