version: "3.8"
services:
    cache:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
    server:
        image: izuna-ytdl:latest
        pull_policy: never
        ports:
            - "5000:5000"
        environment:
            - REDIS_HOST=cache
    web:
        image: nginx:latest
        pull_policy: if_not_present
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
    cache:
        driver: local
