version: "3.8"
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.new
        ports:
            - "8000:8000"
        env_file:
            - .env
    web:
        image: nginx:latest
        pull_policy: if_not_present
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./dist/:/etc/nginx/html/
