version: "3.8"
services:
    redis:
        image: redis/redis-stack:latest
        ports:
            - 6379:6379
            - 8001:8001
        # environment:
        #     - REDIS_ARGS="--requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
        volumes:
            - redis:/data
    server:
        image: izuna-ytdl:latest
        pull_policy: never
        ports:
            - "5000:5000"
        environment:
            - REDIS_OM_URL=redis://redis
        env_file:
            - .env
    web:
        image: nginx:latest
        pull_policy: if_not_present
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
    cache:
        driver: local
    redis:
        driver: local
