version: "3.8"
services:
    server:
        image: izuna-ytdl:latest
        pull_policy: never
        ports:
            - "5000:5000"
        env_file:
            - .env
    web:
        image: nginx:latest
        pull_policy: if_not_present
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./dist/:/etc/nginx/html/
volumes:
    cache:
        driver: local
    redis:
        driver: local
