"""use password hash scheme

Revision ID: fe7a584b0f30
Revises: 4e0446e3ceac
Create Date: 2023-09-02 12:22:45.288331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fe7a584b0f30"
down_revision: Union[str, None] = "4e0446e3ceac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.VARCHAR(), nullable=False))
    op.drop_column("user", "password_hash")
    # ### end Alembic commands ###
